name: tv_shows
description: TV Shows app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  lottie: ^1.2.2
  image_picker: ^0.8.4+11
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.2
  flutter_native_splash: ^2.1.2+1
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.2.0
  provider: ^6.0.2
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  email_validator: ^2.0.1
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
  flutter_gen_runner: ^4.1.6
  flutter_lints: ^1.0.4

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#52368c"
  adaptive_icon_foreground: "assets/images/app_icon-adaptive.png"

flutter_native_splash:
  color: "#52368c"
  image: assets/images/splash_logo.png

flutter_gen:
  line_length: 120

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login_register_screen/
    - assets/images/shows/
    - assets/lottie/
